# Generated by Django 4.2.11 on 2026-09-16 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='exam_year',
        ),
        migrations.RemoveField(
            model_name='question',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='subjectyear',
            name='exam_year',
        ),
        migrations.DeleteModel(
            name='ExamYear',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='SubjectYear',
        ),
    ]
