# Generated by Django 5.2.8 on 2025-11-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.ImageField(upload_to='passports/')),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('subject1', models.CharField(choices=[('English', 'Use of English'), ('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Government', 'Government'), ('Economics', 'Economics'), ('Literature', 'Literature'), ('Commerce', 'Commerce')], max_length=50)),
                ('subject2', models.CharField(choices=[('English', 'Use of English'), ('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Government', 'Government'), ('Economics', 'Economics'), ('Literature', 'Literature'), ('Commerce', 'Commerce')], max_length=50)),
                ('subject3', models.CharField(choices=[('English', 'Use of English'), ('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Government', 'Government'), ('Economics', 'Economics'), ('Literature', 'Literature'), ('Commerce', 'Commerce')], max_length=50)),
                ('subject4', models.CharField(choices=[('English', 'Use of English'), ('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Government', 'Government'), ('Economics', 'Economics'), ('Literature', 'Literature'), ('Commerce', 'Commerce')], max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('cbt_preference', models.CharField(choices=[('Phone', 'Take Test on Phone'), ('Center', 'Practice at Training Center')], max_length=20)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
