# Generated by Django 5.2.8 on 2025-11-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_examyear_examsubject_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='registration_form',
            field=models.FileField(blank=True, null=True, upload_to='candidates/forms/'),
        ),
    ]
