# Generated by Django 5.2.8 on 2025-11-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_candidate_registration_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='subject',
            new_name='exam_subject',
        ),
        migrations.AddField(
            model_name='examsubject',
            name='duration_minutes',
            field=models.IntegerField(default=45),
        ),
    ]
