# Generated by Django 5.2.8 on 2025-11-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_subject_question_exam_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='mark_value',
        ),
        migrations.AddField(
            model_name='candidate',
            name='pin',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='mark',
            field=models.FloatField(default=1.0),
        ),
    ]
