# Generated by Django 4.2.11 on 2026-09-16 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_question_mark_value_candidate_pin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='registration_form',
        ),
    ]
