# Generated by Django 4.2.11 on 2026-09-16 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_candidate_registration_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='exam_subject',
        ),
        migrations.DeleteModel(
            name='ExamSubject',
        ),
        migrations.DeleteModel(
            name='ExamYear',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
