# Generated by Django 4.2.11 on 2026-09-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_question_exam_subject_delete_examsubject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='pin',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
