# Generated by Django 5.2.8 on 2025-11-16 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_remove_question_mark_value_candidate_pin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(blank=True, max_length=120)),
                ('visitor_contact', models.CharField(blank=True, max_length=120)),
                ('text', models.TextField()),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(blank=True, help_text='Optional link to candidate (when known).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.candidate')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
