# Generated by Django 5.2.8 on 2025-11-16 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_question_mark_value_candidate_pin_and_more'),
        ('exam_portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='text',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='read',
            new_name='seen',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='category',
            field=models.CharField(choices=[('support', 'Support'), ('inquiry', 'Inquiry'), ('complaint', 'Complaint')], default='support', max_length=16),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='candidate',
            field=models.ForeignKey(blank=True, help_text='Optional link to candidate (if known).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.candidate'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['created_at'], name='exam_portal_created_57e8b7_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['is_admin'], name='exam_portal_is_admi_66f01b_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['seen'], name='exam_portal_seen_e9405f_idx'),
        ),
    ]
