# Generated by Django 5.2.8 on 2025-11-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_question_mark_value_candidate_pin_and_more'),
        ('exam_portal', '0002_rename_text_chatmessage_message_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['visitor_contact'], name='exam_portal_visitor_a79af1_idx'),
        ),
    ]
