# Generated by Django 4.2.11 on 2026-09-16 14:34

from django.db import migrations, models
import exam_portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_portal', '0003_chatmessage_exam_portal_visitor_a79af1_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='thread_token',
            field=models.CharField(db_index=True, default=exam_portal.models._generate_thread_token, max_length=48),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['thread_token'], name='exam_portal_thread__49cb43_idx'),
        ),
    ]
