# Generated by Django 5.2.8 on 2025-11-08 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubject',
            name='questions_to_display',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='examyear',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/'),
        ),
        migrations.AlterField(
            model_name='examsubject',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='examsubject',
            name='exam_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='exams.examyear'),
        ),
        migrations.AlterField(
            model_name='examyear',
            name='year',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='exam_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.examsubject'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_a',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_b',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_c',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_d',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterUniqueTogether(
            name='examsubject',
            unique_together={('exam_year', 'subject')},
        ),
    ]
