# Generated by Django 5.2.8 on 2025-11-13 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_examsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='current_question_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examsession',
            name='exam_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exams.examyear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examsession',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
