# Generated by Django 5.2.8 on 2025-11-13 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_examsession_current_question_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsession',
            name='exam_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.examyear'),
        ),
    ]
