# Generated by Django 4.2.11 on 2026-09-16 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_candidate_registration_form'),
        ('exams', '0005_alter_examsession_exam_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='UTMESession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('positions', models.JSONField(blank=True, default=dict)),
                ('active_subject_id', models.PositiveIntegerField(blank=True, null=True)),
                ('flagged', models.JSONField(blank=True, default=dict)),
                ('total_duration_minutes', models.PositiveIntegerField(default=130)),
                ('score', models.FloatField(default=0)),
                ('subject_scores', models.JSONField(blank=True, default=dict)),
                ('completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='utme_session', to='accounts.candidate')),
                ('exam_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.examyear')),
                ('subjects', models.ManyToManyField(related_name='utme_sessions', to='exams.examsubject')),
            ],
        ),
        migrations.DeleteModel(
            name='ExamSession',
        ),
    ]
