# Generated by Django 4.2.11 on 2026-09-16 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_utmesession_delete_examsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examsubject',
            name='duration_minutes',
        ),
    ]
